# Generated by Django 4.2 on 2023-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=550)),
                ('choice1', models.CharField(max_length=150)),
                ('choice2', models.CharField(max_length=150)),
                ('choice3', models.CharField(max_length=150)),
                ('choice4', models.CharField(max_length=150)),
                ('trueAnswer', models.CharField(max_length=150)),
            ],
        ),
    ]
