# Generated by Django 4.2 on 2023-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecificquizzdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
